### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by t0biK** [LinusCDE/rmWebUiTools#3]
Hey, 

I really like your project and I would like to add some features.
I currently think about implementing a service that would automatically detect if the Remarkable is plugged in and run the backup automatically (probably with some kind of UI so "normal" users can also use this tool). 

If such features are also of your intereset I would like to be a contributor to prevent always forking the project and wait for a merge.

**Comment by LinusCDE** [comment]
Hi.
First my apology for noticing issue/request this that late.

Initially I had the same idea of making kind of an own file browser with lots of features for it. The problem being that the only language where I can make UIs quite easily being Java/Kotlin.
That was followed by the complication of making decent structured projects in Java (maven and all that stuff) and personal time constraints.

I'll figure out how and assign you as an contributor since I'm currently facing my exam phase which limits my time quite severely. But I'll be happy to help when any questions arise.

**Comment by t0biK** [comment]
I don't have any experience in making UIs in Python either. 
Personally I programm most of the time in Java espacially with Spring which would be also a possible programm language for this kind of project. So if you would like to we can implement everything in Java or keep it as it is. 
I'm also facing my exam phase these days so my spare time is therefore non existent. 
Maybe we could freeze this project until both of us finished the semester.

**Comment by LinusCDE** [comment]
Sounds great.
I have lots of experience with Swing and some JavaFX but never used Swing.
Will be a fun project for sure.

I'm also very happy, continuing the project after exam phase has passed.

P.S.: Do you know Kotlin?

**Comment by bruot** [comment]
Hi @t0biK and @LinusCDE. It looks like you are interested in a GUI browser. Have you seen the (my) [rMExplorer project](https://github.com/bruot/pyrmexplorer/wiki) (Python 3 with PyQt5)?
In its latest version, it can use both the USB and SSH interface and it can do full backups and restoration.

**Comment by LinusCDE** [comment]
Hi @bruot 
that projects looks really promising.  
This issue seems to be forgotten by @t0biK and myself. I personally wasn't really into adding a gui either which also would've meant porting the project to Java. For me it already did everything I wanted and I've kinda forgotten about this.

Since you already have made a UI I don't see any reason persuing this issue.
