### ISSUE TITLE
Feature Requests: Filtering exported files and epub export

### ISSUE THREAD

**Issue by gregeh552** [LinusCDE/rmWebUiTools#4]
1. Export select folders and/or export folder structure only (full export takes too long and my device always crash-reboots)

2. Export original files (Currently a book previously imported as "epub" will only export as huge pdf file, even when there are no notes on it. Is this even possible? Are the original files still there?)

Thanks a lot (!!) for Your work, You saved me a lot of time already with those scripts.

**Comment by LinusCDE** [comment]
Hi,

#### 1.
This is a good idea that I'll commit. I'll commit that asap.

#### 2.
The reMarkable keeps the original epub-file.
I don't know of an option to download that file using the webinterface and thus exeeds the scope of this project.

##### Getting the epub file:
To get that file, you need the internal uuid the device created for it. You can get this using the `paths.py`-script in this repo which shows all uuids with their respective displayed paths.
The epub file will be called `<uuid>.epub` and can be obtained from the device itself (using ssh) or any offical app (any platform) that syncs with your remarkable.
Path to the file:
 - Android app (root needed): `/data/data/com.remarkable.mobile/files`
 - Desktop (Windows): `C:\Users\<YourUser>/AppData/Roaming/remarable/desktop` (path may not be 100% correct since I use the app on wine)
- ReMarkable (using ssh): `/home/root/.local/share/remarkable/xochitl`

Thanks for your request. I can generally add anything the webinterface offers.
Some things will not be apparent there and only visible using the Network-Tab in your browser's developer options (such as [a lot of metadata](https://github.com/LinusCDE/rmWebUiTools/blob/master/.exampleRootMetadata.json)).

#### Note:
> Currently a book previously imported as "epub" will only export as huge pdf file

How big? If it is about 10Mb, thats probably ok.
I export my books in calibe. A 500 pdf export has around 5Mb and marking a lot of text in it and reexporting it only added about 2Mb.
