### ISSUE TITLE
Improper handling of file or folder names

### ISSUE THREAD

**Issue by clemchar78** [LinusCDE/rmWebUiTools#8]
The rm tablets allow you to enter a name that ends with a blank space, but windows does not handle such folder names, crashing the script

**Comment by LinusCDE** [comment]
Hi,

I had not tested it on windows (just assumed it working because python) and also didn't know windows takes issue with trailing whitespace. Regarding windows there would be many potential issues. Since the reMarkable doesn't actually create files with specified names, a lot of things could be inappropriate, especially on windows such as: colons, huge names, backslashes?, ... .

The best approach would probably be to add a proper error message for such problems and let the user rename the file. If I simply remove illegal chars, it could lead to 2 distinct directories being the same on the pc.

While removing trailing space is easy, I'm not sure if it's the best choice to (silently) ignore the error and maybe even cause more unexpected errors because of that.

What would you find ideal? For "/" I already put in some rare similar unicode symbol, so I'm definitely up to replacing/removing the characters, but I'm not sure whether this is ideal in the long run.

**Comment by clemchar78** [comment]
Hi, thanks for coming back to me, I think there should be an error message, as it does not impact the progress of the transfer (since you can just restart) so I'd think that you could add an error message when no folder was found with this name, saying there are illegal chars, as there is also an issue with columns.

**Comment by LinusCDE** [comment]
Good point. Will investigate this tomorrow and add an appropriate error message.
